# Generated by Django 2.1.5 on 2019-02-16 07:10

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields
import modules.core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline_other', models.CharField(help_text='Максимальное кол-во символов: 20', max_length=20, verbose_name='Заголовок')),
                ('text_other', ckeditor_uploader.fields.RichTextUploadingField(help_text='Максимальное кол-во символов: 1000', max_length=1000, verbose_name='Описание')),
                ('headline_your', models.CharField(help_text='Максимальное кол-во символов: 20', max_length=20, verbose_name='Заголовок')),
                ('text_your', ckeditor_uploader.fields.RichTextUploadingField(help_text='Максимальное кол-во символов: 1000', max_length=1000, verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'Категории',
                'verbose_name': 'Категория',
            },
        ),
        migrations.CreateModel(
            name='CommonInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(default=None, help_text='Максимальное кол-во символов: 50', max_length=50, verbose_name='Заголовок в шапке')),
                ('description', models.CharField(default=None, help_text='Максимальное кол-во символов: 300', max_length=300, verbose_name='Описание в шапке')),
                ('footer_text', models.CharField(default=None, help_text='Максимальное кол-во символов: 200', max_length=200, verbose_name='Текст в футере')),
                ('contract_offer', models.FileField(default=None, max_length=1024, upload_to=modules.core.models.CommonInfo.get_file_path, verbose_name='Договор оферты')),
                ('privacy_policy', models.FileField(default=None, max_length=1024, upload_to=modules.core.models.CommonInfo.get_file_path, verbose_name='Политика конфиденциальности')),
                ('number', models.CharField(default=None, help_text='Максимальное кол-во символов: 20', max_length=20, verbose_name='Номер телефона')),
                ('address', models.CharField(default=None, help_text='Максимальное кол-во символов: 100', max_length=100, verbose_name='Адрес')),
                ('map', models.CharField(default=None, help_text='Максимальное кол-во символов: 300', max_length=300, verbose_name='Карта')),
                ('vk_link', models.CharField(help_text='Максимальное кол-во символов: 100', max_length=100, verbose_name='Ссылка на страницу ВК')),
                ('inst_link', models.CharField(help_text='Максимальное кол-во символов: 100', max_length=100, verbose_name='Ссылка на страницу инстаграм')),
            ],
            options={
                'verbose_name_plural': 'Общая информация',
                'verbose_name': 'Общая информация',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(help_text='Максимальное кол-во символов: 50', max_length=50, verbose_name='Название')),
                ('alias', models.SlugField(max_length=225, unique=True, verbose_name='Псевдоним')),
                ('description', models.CharField(help_text='Максимальное кол-во символов: 205', max_length=205, verbose_name='Описание')),
                ('stub', models.ImageField(default=None, help_text='Рекомендуемое разрешение 305x536 px', upload_to=modules.core.models.Course.get_image_path, verbose_name='Фоновое изображение')),
                ('video', embed_video.fields.EmbedVideoField(default=None, verbose_name='Видео')),
                ('schedule', models.CharField(default=None, help_text='Максимальное кол-во символов: 100', max_length=150, verbose_name='Продолжительность курса')),
                ('cost_headlone', models.CharField(default=None, help_text='Максимальное кол-во символов: 60', max_length=60, verbose_name='Стоимость (заголовок)')),
                ('cost_text', models.CharField(default=None, help_text='Максимальное кол-во символов: 100', max_length=200, verbose_name='Стоимость (описание)')),
                ('children', models.BooleanField(default=False, verbose_name='Детский?')),
            ],
            options={
                'verbose_name_plural': 'Курсы',
                'verbose_name': 'Курс',
            },
        ),
        migrations.CreateModel(
            name='CourseAuditory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(default=None, help_text='Только в формате png', upload_to=modules.core.models.CourseAuditory.get_image_path, verbose_name='Логотип')),
                ('headline', models.CharField(help_text='Максимальное кол-во символов: 45', max_length=45, verbose_name='Заголовок')),
                ('text', models.CharField(default=None, help_text='Максимальное кол-во символов: 265', max_length=265, verbose_name='Описание')),
                ('course', models.ForeignKey(on_delete='Выбор курса', related_name='auditory_cours', to='core.Course')),
            ],
            options={
                'verbose_name_plural': 'Заметки о курсе',
                'verbose_name': 'Заметка о курсе',
            },
        ),
        migrations.CreateModel(
            name='CourseCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default=None, help_text='Максимальное кол-во символов: 150', max_length=150, verbose_name='Название урока')),
                ('course', models.ForeignKey(on_delete='Выбор курса', related_name='catalog_cours', to='core.Course')),
            ],
            options={
                'verbose_name_plural': 'Уроки',
                'verbose_name': 'Урок',
            },
        ),
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view', models.BooleanField(default=True, verbose_name='Активен')),
                ('picture', models.ImageField(default=None, help_text='Разрешение - только 126х126 px', upload_to=modules.core.models.CourseReview.get_image_path, verbose_name='Фото рецензента')),
                ('name', models.CharField(help_text='Максимальное кол-во символов: 35', max_length=35, verbose_name='Имя и фамилия')),
                ('text', models.CharField(default=None, help_text='Максимальное кол-во символов: 215', max_length=215, verbose_name='Описание от рецензента')),
                ('course', models.ForeignKey(on_delete='Выбор курса', related_name='cours_review', to='core.Course')),
            ],
            options={
                'verbose_name_plural': 'Отзывы',
                'verbose_name': 'Отзыв',
            },
        ),
        migrations.CreateModel(
            name='CourseSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(default=None, help_text='Ограничение по размеру файла: 1 MB; Рекомендуемое изображение формата 16:9', upload_to=modules.core.models.CourseSkills.get_image_path, verbose_name='Фоновое изображение')),
                ('headline', models.CharField(max_length=200, verbose_name='Наименование')),
                ('text', models.CharField(default=None, max_length=200, verbose_name='Описание')),
                ('course', models.ForeignKey(on_delete='Выбор курса', related_name='skills_cours', to='core.Course')),
            ],
            options={
                'verbose_name_plural': 'Преимущества',
                'verbose_name': 'Преимущество',
            },
        ),
        migrations.CreateModel(
            name='GalleryPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(help_text='Ограничение по размеру 2 MB', upload_to=modules.core.models.GalleryPic.get_image_path, verbose_name='Файл')),
            ],
            options={
                'verbose_name_plural': 'Изображения для галереи',
                'verbose_name': 'Изображение для галереи',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Максимальное кол-во символов: 36', max_length=36, verbose_name='Имя и фамилия')),
                ('post', models.CharField(help_text='Максимальное кол-во символов: 50', max_length=50, verbose_name='Должность')),
                ('photo_manager', models.ImageField(default=None, help_text='Рекомендуемое разрешение 305x536 px', upload_to=modules.core.models.Manager.get_image_path, verbose_name='Фото')),
            ],
            options={
                'verbose_name_plural': 'Преподаватели',
                'verbose_name': 'Преподаватель',
            },
        ),
        migrations.CreateModel(
            name='ManagerNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, help_text='Максимальное кол-во символов: 200', max_length=200, null=True, verbose_name='Заметка')),
                ('manager', models.ForeignKey(on_delete='Руководитель', related_name='manager_note', to='core.Manager')),
            ],
            options={
                'verbose_name_plural': 'Заметки о преподавателе',
                'verbose_name': 'Заметка о преподавателе',
            },
        ),
        migrations.CreateModel(
            name='SimplePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, help_text='Максимальное кол-во символов: 50', max_length=50, verbose_name='Заголовок')),
                ('about_alias', models.SlugField(max_length=225, unique=True, verbose_name='Псевдоним')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(default=None, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'Простые страницы',
                'verbose_name': 'Простая страница',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='manager',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='manager_cours', to='core.Manager', verbose_name='Преподаватель'),
        ),
    ]
