# Generated by Django 2.1.5 on 2019-02-17 07:33

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import modules.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursereview',
            name='view',
        ),
        migrations.AddField(
            model_name='course',
            name='reviews_visible',
            field=models.BooleanField(default=False, null=True, verbose_name='Показать отзывы?'),
        ),
        migrations.AlterField(
            model_name='commoninfo',
            name='address',
            field=models.TextField(verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='commoninfo',
            name='contract_offer',
            field=models.FileField(default=None, help_text='Максимальный размер файла 5 MB', max_length=1024, upload_to=modules.core.models.CommonInfo.get_file_path, verbose_name='Договор оферты'),
        ),
        migrations.AlterField(
            model_name='commoninfo',
            name='description',
            field=models.CharField(default=None, help_text='Максимальное кол-во символов: 205', max_length=205, verbose_name='Описание в шапке'),
        ),
        migrations.AlterField(
            model_name='commoninfo',
            name='footer_text',
            field=models.TextField(verbose_name='Текст в футере'),
        ),
        migrations.AlterField(
            model_name='commoninfo',
            name='inst_link',
            field=models.TextField(help_text='Ссылка должна начинаться с https://', verbose_name='Ссылка на страницу инстаграм'),
        ),
        migrations.AlterField(
            model_name='commoninfo',
            name='map',
            field=models.TextField(help_text='Cгенерированный код на сайте https://yandex.ru/map-constructor/', verbose_name='Карта'),
        ),
        migrations.AlterField(
            model_name='commoninfo',
            name='number',
            field=models.CharField(default=None, max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='commoninfo',
            name='privacy_policy',
            field=models.FileField(default=None, help_text='Максимальный размер файла 5 MB', max_length=1024, upload_to=modules.core.models.CommonInfo.get_file_path, verbose_name='Политика конфиденциальности'),
        ),
        migrations.AlterField(
            model_name='commoninfo',
            name='vk_link',
            field=models.TextField(help_text='Ссылка должна начинаться с https://', verbose_name='Ссылка на страницу ВК'),
        ),
        migrations.AlterField(
            model_name='course',
            name='cost_text',
            field=models.TextField(default=None, verbose_name='Стоимость (описание)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_cours', to='core.Manager', verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='course',
            name='schedule',
            field=models.TextField(default=None, verbose_name='Продолжительность курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='stub',
            field=models.ImageField(default=None, upload_to=modules.core.models.Course.get_image_path, verbose_name='Фоновое изображение'),
        ),
        migrations.AlterField(
            model_name='courseauditory',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditory_cours', to='core.Course'),
        ),
        migrations.AlterField(
            model_name='courseauditory',
            name='icon',
            field=models.ImageField(default=None, help_text='Рекомендуемое разрешение: 105x105 px; изображение в формате png', upload_to=modules.core.models.CourseAuditory.get_image_path, verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='coursecatalog',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_cours', to='core.Course'),
        ),
        migrations.AlterField(
            model_name='coursecatalog',
            name='text',
            field=models.TextField(verbose_name='Название урока'),
        ),
        migrations.AlterField(
            model_name='coursereview',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours_review', to='core.Course'),
        ),
        migrations.AlterField(
            model_name='coursereview',
            name='picture',
            field=models.ImageField(default=None, help_text='Рекомендуемое разрешение: 126x126 px', upload_to=modules.core.models.CourseReview.get_image_path, verbose_name='Фото рецензента'),
        ),
        migrations.AlterField(
            model_name='courseskills',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills_cours', to='core.Course'),
        ),
        migrations.AlterField(
            model_name='courseskills',
            name='headline',
            field=models.CharField(help_text='Максимальное кол-во символов: 55', max_length=55, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='courseskills',
            name='picture',
            field=models.ImageField(default=None, help_text='Максимальный размер файла 1 MB; изображение формата 16:9', upload_to=modules.core.models.CourseSkills.get_image_path, verbose_name='Фоновое изображение'),
        ),
        migrations.AlterField(
            model_name='courseskills',
            name='text',
            field=models.CharField(default=None, help_text='Максимальное кол-во символов: 215', max_length=215, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='gallerypic',
            name='pic',
            field=models.ImageField(help_text='Максимальный размер файла 1 MB', upload_to=modules.core.models.GalleryPic.get_image_path, verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='photo_manager',
            field=models.ImageField(default=None, help_text='Рекомендуемое разрешение: 305x536 px', upload_to=modules.core.models.Manager.get_image_path, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='managernote',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_note', to='core.Manager'),
        ),
        migrations.AlterField(
            model_name='managernote',
            name='notes',
            field=models.TextField(default=False, verbose_name='Заметка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='simplepage',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=None, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='simplepage',
            name='title',
            field=models.TextField(default=None, verbose_name='Заголовок'),
        ),
    ]
