# Generated by Django 2.1.5 on 2019-02-19 08:41

from django.db import migrations, models
import modules.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190217_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commoninfo',
            name='contract_offer',
            field=models.FileField(default=None, help_text='Максимальный размер файла 5 MB', upload_to=modules.core.models.CommonInfo.get_file_path, validators=[modules.core.models.CommonInfo.file_size], verbose_name='Договор оферты'),
        ),
        migrations.AlterField(
            model_name='commoninfo',
            name='privacy_policy',
            field=models.FileField(default=None, help_text='Максимальный размер файла 5 MB', upload_to=modules.core.models.CommonInfo.get_file_path, validators=[modules.core.models.CommonInfo.file_size], verbose_name='Политика конфиденциальности'),
        ),
        migrations.AlterField(
            model_name='course',
            name='reviews_visible',
            field=models.BooleanField(default=False, verbose_name='Показать отзывы?'),
        ),
        migrations.AlterField(
            model_name='course',
            name='stub',
            field=models.ImageField(default=None, help_text='Максимальный размер файла 1 MB; изображение формата 16:9', upload_to=modules.core.models.Course.get_image_path, validators=[modules.core.models.Course.file_size], verbose_name='Фоновое изображение'),
        ),
        migrations.AlterField(
            model_name='courseskills',
            name='picture',
            field=models.ImageField(default=None, help_text='Максимальный размер файла 1 MB; изображение формата 16:9', upload_to=modules.core.models.CourseSkills.get_image_path, validators=[modules.core.models.CourseSkills.file_size], verbose_name='Фоновое изображение'),
        ),
    ]
